"""db migrate

Revision ID: 4e8a50c99953
Revises: 8f301d369592
Create Date: 2026-02-14 23:26:33.629886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8a50c99953'
down_revision: Union[str, Sequence[str], None] = '8f301d369592'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('context_conflict',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relation_chain_id', sa.Integer(), nullable=False, comment='关联关系链ID'),
    sa.Column('former_context_id', sa.Integer(), nullable=False, comment='前者上下文ID'),
    sa.Column('latter_context_id', sa.Integer(), nullable=False, comment='后者上下文ID'),
    sa.Column('conflict_reason', sa.Text(), nullable=True, comment='冲突原因'),
    sa.Column('resolution_status', sa.Enum('PENDING', 'RESOLVED_KEEP_NEW', 'RESOLVED_KEEP_OLD', 'BOTH_DOWNGRADED', name='conflictresolutionstatus'), nullable=False, comment='冲突解决状态'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='冲突创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='冲突更新时间'),
    sa.ForeignKeyConstraint(['former_context_id'], ['context.id'], name=op.f('fk_context_conflict_former_context_id_context'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['latter_context_id'], ['context.id'], name=op.f('fk_context_conflict_latter_context_id_context'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_chain_id'], ['relation_chain.id'], name=op.f('fk_context_conflict_relation_chain_id_relation_chain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_conflict'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('context_conflict')
    # ### end Alembic commands ###
