"""db migrate

Revision ID: 87891cc18436
Revises: 4e8a50c99953
Create Date: 2026-02-15 01:54:01.225079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87891cc18436'
down_revision: Union[str, Sequence[str], None] = '4e8a50c99953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_context_created_at'), 'context', ['created_at'], unique=False)
    op.create_index(op.f('ix_context_last_used_at'), 'context', ['last_used_at'], unique=False)
    op.create_index(op.f('ix_context_relation_chain_id'), 'context', ['relation_chain_id'], unique=False)
    op.create_index(op.f('ix_context_type'), 'context', ['type'], unique=False)
    op.create_index(op.f('ix_context_weight'), 'context', ['weight'], unique=False)
    op.create_index(op.f('ix_relation_chain_crush_id'), 'relation_chain', ['crush_id'], unique=False)
    op.create_index(op.f('ix_relation_chain_user_id'), 'relation_chain', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relation_chain_user_id'), table_name='relation_chain')
    op.drop_index(op.f('ix_relation_chain_crush_id'), table_name='relation_chain')
    op.drop_index(op.f('ix_context_weight'), table_name='context')
    op.drop_index(op.f('ix_context_type'), table_name='context')
    op.drop_index(op.f('ix_context_relation_chain_id'), table_name='context')
    op.drop_index(op.f('ix_context_last_used_at'), table_name='context')
    op.drop_index(op.f('ix_context_created_at'), table_name='context')
    # ### end Alembic commands ###
