"""db migrate

Revision ID: 8ad002823cb7
Revises: 87891cc18436
Create Date: 2026-02-15 02:16:11.014062

"""
from typing import Sequence, Union
import pgvector

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad002823cb7'
down_revision: Union[str, Sequence[str], None] = '87891cc18436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('context_embedding',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('context_id', sa.Integer(), nullable=False, comment='关联上下文ID'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment='Embedding模型名称'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False, comment='向量表示'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.ForeignKeyConstraint(['context_id'], ['context.id'], name=op.f('fk_context_embedding_context_id_context'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context_embedding'))
    )
    op.drop_constraint(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', type_='foreignkey')
    op.create_foreign_key(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', 'crush', ['crush_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', type_='foreignkey')
    op.create_foreign_key(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', 'crush', ['crush_id'], ['id'], ondelete='SET NULL')
    op.drop_table('context_embedding')
    # ### end Alembic commands ###
