"""db migrate

Revision ID: 8b5d99771745
Revises: d28fbb9f01b4
Create Date: 2026-02-14 11:17:59.012888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b5d99771745'
down_revision: Union[str, Sequence[str], None] = 'd28fbb9f01b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relation_chain',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='关联用户ID'),
    sa.Column('crush_name', sa.String(length=64), nullable=False, comment='Crush 姓名'),
    sa.Column('crush_gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='usergender'), nullable=False, comment='Crush 性别'),
    sa.Column('crush_mbti', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbti'), nullable=True, comment='Crush MBTI 类型'),
    sa.Column('crush_personality_tags', postgresql.ARRAY(sa.Text()), nullable=False, comment='Crush 性格标签'),
    sa.Column('current_stage', sa.Enum('STRANGER', 'FRIEND', 'AMBIGUOUS', 'DATING', 'TENSION', 'BROKEN_UP', 'FAILED', name='relationstage'), nullable=False, comment='当前关系阶段'),
    sa.Column('stage_confidence', sa.Float(), nullable=False, comment='当前关系阶段置信度'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否进行中'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='关系链创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='关系链更新时间'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_relation_chain_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relation_chain'))
    )
    op.create_table('context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relation_chain_id', sa.Integer(), nullable=False, comment='关联关系链ID'),
    sa.Column('type', sa.Enum('STATIC_PROFILE', 'CHAT_LOG', 'INTERACTION_SIGNAL', 'DERIVED_INSIGHT', 'STAGE_EVENT', 'SYSTEM_ANALYSIS', name='contexttype'), nullable=False, comment='Context类型'),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False, comment='Context内容'),
    sa.Column('weight', sa.Float(), nullable=False, comment='Context 权重（影响力）'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Context 置信度（可靠性）'),
    sa.Column('summary', sa.Text(), nullable=True, comment='Context 摘要'),
    sa.Column('source', sa.Enum('user_input', 'system_inference', 'llm_generated', 'external_api', name='contextsource'), nullable=False, comment='Context 来源'),
    sa.Column('derived_from_context_id', sa.Integer(), nullable=True, comment='来源上下文ID（如果是派生上下文）'),
    sa.Column('is_conflicted', sa.Boolean(), nullable=False, comment='是否与其他上下文冲突'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='上下文创建时间'),
    sa.ForeignKeyConstraint(['derived_from_context_id'], ['context.id'], name=op.f('fk_context_derived_from_context_id_context'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relation_chain_id'], ['relation_chain.id'], name=op.f('fk_context_relation_chain_id_relation_chain'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_context'))
    )
    op.create_table('chain_stage_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('relation_chain_id', sa.Integer(), nullable=False, comment='关联关系链ID'),
    sa.Column('trigger_context_id', sa.Integer(), nullable=True, comment='触发变更的上下文ID'),
    sa.Column('previous_stage', sa.Enum('STRANGER', 'FRIEND', 'AMBIGUOUS', 'DATING', 'TENSION', 'BROKEN_UP', 'FAILED', name='relationstage'), nullable=True, comment='变更前的关系阶段'),
    sa.Column('new_stage', sa.Enum('STRANGER', 'FRIEND', 'AMBIGUOUS', 'DATING', 'TENSION', 'BROKEN_UP', 'FAILED', name='relationstage'), nullable=False, comment='变更后的关系阶段'),
    sa.Column('trigger_reason', sa.Text(), nullable=True, comment='触发变更的原因'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='变更后的关系阶段置信度'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='变更时间'),
    sa.ForeignKeyConstraint(['relation_chain_id'], ['relation_chain.id'], name=op.f('fk_chain_stage_history_relation_chain_id_relation_chain'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_context_id'], ['context.id'], name=op.f('fk_chain_stage_history_trigger_context_id_context'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_stage_history'))
    )
    op.add_column('user', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='usergender'), nullable=False, comment='用户性别'))
    op.add_column('user', sa.Column('mbti', sa.Enum('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbti'), nullable=True, comment='用户MBTI类型'))
    op.add_column('user', sa.Column('personality_tags', postgresql.ARRAY(sa.Text()), nullable=False, comment='用户性格标签'))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment='用户唯一用户名',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               comment='用户密码',
               existing_nullable=False)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment='用户昵称',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=128),
               comment='用户邮箱',
               existing_nullable=True)
    op.alter_column('user', 'level',
               existing_type=postgresql.ENUM('L0', 'L1', 'L2', 'L3', 'L4', name='userlevel'),
               comment='用户等级',
               existing_nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment='用户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='用户创建时间',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user', 'level',
               existing_type=postgresql.ENUM('L0', 'L1', 'L2', 'L3', 'L4', name='userlevel'),
               comment=None,
               existing_comment='用户等级',
               existing_nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='用户邮箱',
               existing_nullable=True)
    op.alter_column('user', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='用户昵称',
               existing_nullable=True)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='用户密码',
               existing_nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='用户唯一用户名',
               existing_nullable=False)
    op.drop_column('user', 'personality_tags')
    op.drop_column('user', 'mbti')
    op.drop_column('user', 'gender')
    op.drop_table('chain_stage_history')
    op.drop_table('context')
    op.drop_table('relation_chain')
    # ### end Alembic commands ###
