"""db migrate

Revision ID: c4f24380c682
Revises: 8b5d99771745
Create Date: 2026-02-14 21:38:31.844057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4f24380c682'
down_revision: Union[str, Sequence[str], None] = '8b5d99771745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    usergender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='usergender', create_type=False)
    mbti_enum = postgresql.ENUM('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbti', create_type=False)
    op.create_table('crush',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Crush 姓名'),
    sa.Column('gender', usergender_enum, nullable=False, comment='Crush 性别'),
    sa.Column('mbti', mbti_enum, nullable=True, comment='Crush MBTI 类型'),
    sa.Column('personality_tags', postgresql.ARRAY(sa.Text()), nullable=False, comment='Crush 性格标签'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Crush 创建时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crush'))
    )
    op.add_column('context', sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'))
    op.add_column('relation_chain', sa.Column('crush_id', sa.Integer(), nullable=False, comment='关联CrushID'))
    op.create_unique_constraint('uq_user_crush_relation', 'relation_chain', ['user_id', 'crush_id'])
    op.create_foreign_key(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', 'crush', ['crush_id'], ['id'], ondelete='SET NULL')
    op.drop_column('relation_chain', 'crush_gender')
    op.drop_column('relation_chain', 'crush_mbti')
    op.drop_column('relation_chain', 'crush_personality_tags')
    op.drop_column('relation_chain', 'crush_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    usergender_enum = postgresql.ENUM('MALE', 'FEMALE', 'OTHER', name='usergender', create_type=False)
    mbti_enum = postgresql.ENUM('ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP', 'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ', name='mbti', create_type=False)
    op.add_column('relation_chain', sa.Column('crush_name', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Crush 姓名'))
    op.add_column('relation_chain', sa.Column('crush_personality_tags', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False, comment='Crush 性格标签'))
    op.add_column('relation_chain', sa.Column('crush_mbti', mbti_enum, autoincrement=False, nullable=True, comment='Crush MBTI 类型'))
    op.add_column('relation_chain', sa.Column('crush_gender', usergender_enum, autoincrement=False, nullable=False, comment='Crush 性别'))
    op.drop_constraint(op.f('fk_relation_chain_crush_id_crush'), 'relation_chain', type_='foreignkey')
    op.drop_constraint('uq_user_crush_relation', 'relation_chain', type_='unique')
    op.drop_column('relation_chain', 'crush_id')
    op.drop_column('context', 'last_used_at')
    op.drop_table('crush')
    # ### end Alembic commands ###
